# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/honza/code/g4application

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/honza/code/g4application

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/honza/code/g4application/CMakeFiles /home/honza/code/g4application/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/honza/code/g4application/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named g4

# Build rule for target.
g4: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 g4
.PHONY : g4

# fast build rule for target.
g4/fast:
	$(MAKE) -f CMakeFiles/g4.dir/build.make CMakeFiles/g4.dir/build
.PHONY : g4/fast

#=============================================================================
# Target rules for targets named g4App

# Build rule for target.
g4App: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 g4App
.PHONY : g4App

# fast build rule for target.
g4App/fast:
	$(MAKE) -f CMakeFiles/g4App.dir/build.make CMakeFiles/g4App.dir/build
.PHONY : g4App/fast

g4.o: g4.cc.o
.PHONY : g4.o

# target to build an object file
g4.cc.o:
	$(MAKE) -f CMakeFiles/g4.dir/build.make CMakeFiles/g4.dir/g4.cc.o
.PHONY : g4.cc.o

g4.i: g4.cc.i
.PHONY : g4.i

# target to preprocess a source file
g4.cc.i:
	$(MAKE) -f CMakeFiles/g4.dir/build.make CMakeFiles/g4.dir/g4.cc.i
.PHONY : g4.cc.i

g4.s: g4.cc.s
.PHONY : g4.s

# target to generate assembly for a file
g4.cc.s:
	$(MAKE) -f CMakeFiles/g4.dir/build.make CMakeFiles/g4.dir/g4.cc.s
.PHONY : g4.cc.s

src/ApplicationConfiguration.o: src/ApplicationConfiguration.cc.o
.PHONY : src/ApplicationConfiguration.o

# target to build an object file
src/ApplicationConfiguration.cc.o:
	$(MAKE) -f CMakeFiles/g4App.dir/build.make CMakeFiles/g4App.dir/src/ApplicationConfiguration.cc.o
.PHONY : src/ApplicationConfiguration.cc.o

src/ApplicationConfiguration.i: src/ApplicationConfiguration.cc.i
.PHONY : src/ApplicationConfiguration.i

# target to preprocess a source file
src/ApplicationConfiguration.cc.i:
	$(MAKE) -f CMakeFiles/g4App.dir/build.make CMakeFiles/g4App.dir/src/ApplicationConfiguration.cc.i
.PHONY : src/ApplicationConfiguration.cc.i

src/ApplicationConfiguration.s: src/ApplicationConfiguration.cc.s
.PHONY : src/ApplicationConfiguration.s

# target to generate assembly for a file
src/ApplicationConfiguration.cc.s:
	$(MAKE) -f CMakeFiles/g4App.dir/build.make CMakeFiles/g4App.dir/src/ApplicationConfiguration.cc.s
.PHONY : src/ApplicationConfiguration.cc.s

src/ApplicationMessenger.o: src/ApplicationMessenger.cc.o
.PHONY : src/ApplicationMessenger.o

# target to build an object file
src/ApplicationMessenger.cc.o:
	$(MAKE) -f CMakeFiles/g4App.dir/build.make CMakeFiles/g4App.dir/src/ApplicationMessenger.cc.o
.PHONY : src/ApplicationMessenger.cc.o

src/ApplicationMessenger.i: src/ApplicationMessenger.cc.i
.PHONY : src/ApplicationMessenger.i

# target to preprocess a source file
src/ApplicationMessenger.cc.i:
	$(MAKE) -f CMakeFiles/g4App.dir/build.make CMakeFiles/g4App.dir/src/ApplicationMessenger.cc.i
.PHONY : src/ApplicationMessenger.cc.i

src/ApplicationMessenger.s: src/ApplicationMessenger.cc.s
.PHONY : src/ApplicationMessenger.s

# target to generate assembly for a file
src/ApplicationMessenger.cc.s:
	$(MAKE) -f CMakeFiles/g4App.dir/build.make CMakeFiles/g4App.dir/src/ApplicationMessenger.cc.s
.PHONY : src/ApplicationMessenger.cc.s

src/G4Application.o: src/G4Application.cc.o
.PHONY : src/G4Application.o

# target to build an object file
src/G4Application.cc.o:
	$(MAKE) -f CMakeFiles/g4App.dir/build.make CMakeFiles/g4App.dir/src/G4Application.cc.o
.PHONY : src/G4Application.cc.o

src/G4Application.i: src/G4Application.cc.i
.PHONY : src/G4Application.i

# target to preprocess a source file
src/G4Application.cc.i:
	$(MAKE) -f CMakeFiles/g4App.dir/build.make CMakeFiles/g4App.dir/src/G4Application.cc.i
.PHONY : src/G4Application.cc.i

src/G4Application.s: src/G4Application.cc.s
.PHONY : src/G4Application.s

# target to generate assembly for a file
src/G4Application.cc.s:
	$(MAKE) -f CMakeFiles/g4App.dir/build.make CMakeFiles/g4App.dir/src/G4Application.cc.s
.PHONY : src/G4Application.cc.s

src/GeometryBuilder.o: src/GeometryBuilder.cc.o
.PHONY : src/GeometryBuilder.o

# target to build an object file
src/GeometryBuilder.cc.o:
	$(MAKE) -f CMakeFiles/g4App.dir/build.make CMakeFiles/g4App.dir/src/GeometryBuilder.cc.o
.PHONY : src/GeometryBuilder.cc.o

src/GeometryBuilder.i: src/GeometryBuilder.cc.i
.PHONY : src/GeometryBuilder.i

# target to preprocess a source file
src/GeometryBuilder.cc.i:
	$(MAKE) -f CMakeFiles/g4App.dir/build.make CMakeFiles/g4App.dir/src/GeometryBuilder.cc.i
.PHONY : src/GeometryBuilder.cc.i

src/GeometryBuilder.s: src/GeometryBuilder.cc.s
.PHONY : src/GeometryBuilder.s

# target to generate assembly for a file
src/GeometryBuilder.cc.s:
	$(MAKE) -f CMakeFiles/g4App.dir/build.make CMakeFiles/g4App.dir/src/GeometryBuilder.cc.s
.PHONY : src/GeometryBuilder.cc.s

src/NumberingEventAction.o: src/NumberingEventAction.cc.o
.PHONY : src/NumberingEventAction.o

# target to build an object file
src/NumberingEventAction.cc.o:
	$(MAKE) -f CMakeFiles/g4App.dir/build.make CMakeFiles/g4App.dir/src/NumberingEventAction.cc.o
.PHONY : src/NumberingEventAction.cc.o

src/NumberingEventAction.i: src/NumberingEventAction.cc.i
.PHONY : src/NumberingEventAction.i

# target to preprocess a source file
src/NumberingEventAction.cc.i:
	$(MAKE) -f CMakeFiles/g4App.dir/build.make CMakeFiles/g4App.dir/src/NumberingEventAction.cc.i
.PHONY : src/NumberingEventAction.cc.i

src/NumberingEventAction.s: src/NumberingEventAction.cc.s
.PHONY : src/NumberingEventAction.s

# target to generate assembly for a file
src/NumberingEventAction.cc.s:
	$(MAKE) -f CMakeFiles/g4App.dir/build.make CMakeFiles/g4App.dir/src/NumberingEventAction.cc.s
.PHONY : src/NumberingEventAction.cc.s

src/PluggableGeometry.o: src/PluggableGeometry.cc.o
.PHONY : src/PluggableGeometry.o

# target to build an object file
src/PluggableGeometry.cc.o:
	$(MAKE) -f CMakeFiles/g4App.dir/build.make CMakeFiles/g4App.dir/src/PluggableGeometry.cc.o
.PHONY : src/PluggableGeometry.cc.o

src/PluggableGeometry.i: src/PluggableGeometry.cc.i
.PHONY : src/PluggableGeometry.i

# target to preprocess a source file
src/PluggableGeometry.cc.i:
	$(MAKE) -f CMakeFiles/g4App.dir/build.make CMakeFiles/g4App.dir/src/PluggableGeometry.cc.i
.PHONY : src/PluggableGeometry.cc.i

src/PluggableGeometry.s: src/PluggableGeometry.cc.s
.PHONY : src/PluggableGeometry.s

# target to generate assembly for a file
src/PluggableGeometry.cc.s:
	$(MAKE) -f CMakeFiles/g4App.dir/build.make CMakeFiles/g4App.dir/src/PluggableGeometry.cc.s
.PHONY : src/PluggableGeometry.cc.s

src/PluginLoader.o: src/PluginLoader.cc.o
.PHONY : src/PluginLoader.o

# target to build an object file
src/PluginLoader.cc.o:
	$(MAKE) -f CMakeFiles/g4App.dir/build.make CMakeFiles/g4App.dir/src/PluginLoader.cc.o
.PHONY : src/PluginLoader.cc.o

src/PluginLoader.i: src/PluginLoader.cc.i
.PHONY : src/PluginLoader.i

# target to preprocess a source file
src/PluginLoader.cc.i:
	$(MAKE) -f CMakeFiles/g4App.dir/build.make CMakeFiles/g4App.dir/src/PluginLoader.cc.i
.PHONY : src/PluginLoader.cc.i

src/PluginLoader.s: src/PluginLoader.cc.s
.PHONY : src/PluginLoader.s

# target to generate assembly for a file
src/PluginLoader.cc.s:
	$(MAKE) -f CMakeFiles/g4App.dir/build.make CMakeFiles/g4App.dir/src/PluginLoader.cc.s
.PHONY : src/PluginLoader.cc.s

src/PluginMessenger.o: src/PluginMessenger.cc.o
.PHONY : src/PluginMessenger.o

# target to build an object file
src/PluginMessenger.cc.o:
	$(MAKE) -f CMakeFiles/g4App.dir/build.make CMakeFiles/g4App.dir/src/PluginMessenger.cc.o
.PHONY : src/PluginMessenger.cc.o

src/PluginMessenger.i: src/PluginMessenger.cc.i
.PHONY : src/PluginMessenger.i

# target to preprocess a source file
src/PluginMessenger.cc.i:
	$(MAKE) -f CMakeFiles/g4App.dir/build.make CMakeFiles/g4App.dir/src/PluginMessenger.cc.i
.PHONY : src/PluginMessenger.cc.i

src/PluginMessenger.s: src/PluginMessenger.cc.s
.PHONY : src/PluginMessenger.s

# target to generate assembly for a file
src/PluginMessenger.cc.s:
	$(MAKE) -f CMakeFiles/g4App.dir/build.make CMakeFiles/g4App.dir/src/PluginMessenger.cc.s
.PHONY : src/PluginMessenger.cc.s

src/RunManager.o: src/RunManager.cc.o
.PHONY : src/RunManager.o

# target to build an object file
src/RunManager.cc.o:
	$(MAKE) -f CMakeFiles/g4App.dir/build.make CMakeFiles/g4App.dir/src/RunManager.cc.o
.PHONY : src/RunManager.cc.o

src/RunManager.i: src/RunManager.cc.i
.PHONY : src/RunManager.i

# target to preprocess a source file
src/RunManager.cc.i:
	$(MAKE) -f CMakeFiles/g4App.dir/build.make CMakeFiles/g4App.dir/src/RunManager.cc.i
.PHONY : src/RunManager.cc.i

src/RunManager.s: src/RunManager.cc.s
.PHONY : src/RunManager.s

# target to generate assembly for a file
src/RunManager.cc.s:
	$(MAKE) -f CMakeFiles/g4App.dir/build.make CMakeFiles/g4App.dir/src/RunManager.cc.s
.PHONY : src/RunManager.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... g4"
	@echo "... g4App"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... g4.o"
	@echo "... g4.i"
	@echo "... g4.s"
	@echo "... src/ApplicationConfiguration.o"
	@echo "... src/ApplicationConfiguration.i"
	@echo "... src/ApplicationConfiguration.s"
	@echo "... src/ApplicationMessenger.o"
	@echo "... src/ApplicationMessenger.i"
	@echo "... src/ApplicationMessenger.s"
	@echo "... src/G4Application.o"
	@echo "... src/G4Application.i"
	@echo "... src/G4Application.s"
	@echo "... src/GeometryBuilder.o"
	@echo "... src/GeometryBuilder.i"
	@echo "... src/GeometryBuilder.s"
	@echo "... src/NumberingEventAction.o"
	@echo "... src/NumberingEventAction.i"
	@echo "... src/NumberingEventAction.s"
	@echo "... src/PluggableGeometry.o"
	@echo "... src/PluggableGeometry.i"
	@echo "... src/PluggableGeometry.s"
	@echo "... src/PluginLoader.o"
	@echo "... src/PluginLoader.i"
	@echo "... src/PluginLoader.s"
	@echo "... src/PluginMessenger.o"
	@echo "... src/PluginMessenger.i"
	@echo "... src/PluginMessenger.s"
	@echo "... src/RunManager.o"
	@echo "... src/RunManager.i"
	@echo "... src/RunManager.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

