/component/builtin DefaultWorld
/component/builtin ReferencePhysicsList
/component/builtin GPS
/component/builtin EventNumberLogging
/component/builtin MemoryLogging

/conf/setDouble generator.energy 0.5
/conf/setString component.ReferencePhysicsList.listName FTFP_BERT

/plugin/open rotationTest
/plugin/load rotationTest active

/component/list

/run/initialize

# /vis/scene/create
# /vis/open OGLSQt
# /vis/drawVolume
