#!/usr/bin/env g4
/component/verbose 1
/plugin/verbose 1

/component/builtin DefaultWorld
/component/builtin ReferencePhysicsList
/component/builtin GPS
/component/builtin EventNumberLogging
/component/builtin MemoryLogging

/conf/setDouble generator.energy 0.5
/conf/setString component.ReferencePhysicsList.listName FTFP_BERT_LIV

/plugin/open parallelTest
/plugin/load parallelTest parallel1
/plugin/load parallelTest parallel2

/component/list

/run/initialize
/run/beamOn 10
