#!/usr/bin/env g4
/app/addComponent DefaultWorld
/app/addComponent ReferencePhysicsList
/app/addComponent GPS
/app/addComponent EventNumberLogging
/app/addComponent MemoryLogging

/conf/setDouble generator.energy 0.5
/conf/setString component.ReferencePhysicsList.listName FTFP_BERT

/plugin/open parallelTest
/plugin/load parallelTest parallel1
/plugin/load parallelTest parallel2

/component/list

/run/initialize
/run/beamOn 10