# Load the plugin
/plugin/open libsimplePlugin.so
/plugin/loadAll simplePlugin

/app/addComponent ReferencePhysicsList
/app/addComponent DefaultWorld

/conf/setString component.ReferencePhysicsList.listName FTFP_BERT

# Set a configuration value
/conf/setDouble generator.energy 0.5

# Run
/run/initialize

# Visualize one trajectory and wait for user pressing Enter...
/vis/open OGLSQt
/vis/drawVolume
/vis/scene/add/trajectories
/run/beamOn 1
