# Load the plugins
/plugin/open libsimplePlugin.so
/plugin/open libhttpPlugin.so
/plugin/loadAll httpPlugin
/plugin/loadAll simplePlugin

/component/builtin ReferencePhysicsList
/component/builtin DefaultWorld

/conf/setString component.ReferencePhysicsList.listName FTFP_BERT

# Set a configuration value
/conf/setDouble generator.energy 0.5

/conf/setInt http.port 7777

# Run
/run/initialize
/run/beamOn 10000000
